services:
  app:
    build: .
    container_name: code-editing-agent
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
      - /app/vendor
    working_dir: /app
    ports:
      - "8080:8080"
    command: ["go", "run", "main.go"]
    
  # 用于运行测试的服务
  test:
    build: .
    container_name: code-editing-agent-test
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "test", "-v", "./..."]
    
  # 用于运行覆盖率测试的服务
  coverage:
    build: .
    container_name: code-editing-agent-coverage
    volumes:
      - .:/app
      - ./coverage:/app/coverage
    working_dir: /app
    command: >
      sh -c "
        go test -v -race -coverprofile=coverage/coverage.out -covermode=atomic ./... &&
        go tool cover -html=coverage/coverage.out -o coverage/coverage.html &&
        go tool cover -func=coverage/coverage.out
      "
